version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    container_name: pterodactyl-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: panel
      MYSQL_USER: ptero
      MYSQL_PASSWORD: password
    volumes:
      - ./mariadb:/var/lib/mysql

  panel:
    image: ghcr.io/pterodactyl/panel:latest
    container_name: pterodactyl
    restart: always
    depends_on:
      - mariadb
    environment:
      APP_URL: http://localhost
      APP_ENV: production
      APP_KEY: base64:xGc8u...   # nanti diganti hasil generate
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: ptero
      DB_PASSWORD: password
    volumes:
      - ./panel:/app
    ports:
      - "8080:80"

  wings:
    image: ghcr.io/pterodactyl/wings:latest
    container_name: pterodactyl-wings
    restart: always
    privileged: true
    depends_on:
      - panel
    environment:
      WINGS_CONFIG: /etc/pterodactyl/config.yml
    volumes:
      - ./wings:/etc/pterodactyl
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/pterodactyl:/tmp/pterodactyl
    ports:
      - "2022:2022"
      - "8081:8080"
