version: '3.8'

services:
  panel:
    image: ghcr.io/pterodactyl/panel:latest
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      APP_ENV: production
      APP_URL: http://localhost
      APP_TIMEZONE: UTC
      APP_SERVICE_AUTHOR: "admin@example.com"

      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: panel
      DB_USERNAME: pterodactyl
      DB_PASSWORD: passwordku

      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_DRIVER: redis
      REDIS_HOST: redis

    volumes:
      - ./panel:/app/var
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.6
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: panel
      MYSQL_USER: pterodactyl
      MYSQL_PASSWORD: passwordku
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: unless-stopped

volumes:
  db_data:
